// Browser-level UI checks. Run with PLAYWRIGHT_PACKAGE pointing to an installed playwright package if it is not a project dependency.
import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {spawnSync} from 'node:child_process';
const modulePath=process.env.PLAYWRIGHT_PACKAGE;
const {chromium}=await import(modulePath?pathToFileURL(resolve(modulePath,'index.mjs')).href:'playwright');
const browser=await chromium.launch({headless:true,channel:'chrome'});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.addInitScript(()=>localStorage.setItem('depthdesk-demo',JSON.stringify({onboardingDone:true,startupWorkspace:'depth'})));
await page.goto(process.env.UI_TEST_URL??'http://127.0.0.1:5173');
await page.getByRole('heading',{name:'MagiDepth',exact:true}).waitFor();
assert.equal(await page.getByRole('button',{name:'1개 맵 영상 내보내기'}).isDisabled(),true);
assert.equal(await page.getByRole('checkbox',{name:'Normal 표면 방향 추출'}).isDisabled(),true);
await page.getByRole('checkbox',{name:'Base Color 기본 색상 추출'}).click();
assert.equal(await page.getByRole('checkbox',{name:'Base Color 기본 색상 추출'}).getAttribute('aria-checked'),'true');
await page.getByRole('tab',{name:'Base Color',exact:true}).click();
await page.getByRole('button',{name:'고급 AI',exact:true}).click();
await page.getByText('Marigold AI로 Normal·재질 맵을 추정합니다.',{exact:false}).waitFor();
await page.getByRole('button',{name:'테마 전환'}).click();
assert.equal(await page.locator('html').evaluate(e=>e.classList.contains('dark')),false);
await page.getByRole('button',{name:'앱 설정',exact:true}).click();
await page.getByRole('dialog').waitFor();
await page.getByRole('button',{name:'닫기',exact:true}).click();
await page.getByRole('button',{name:'튜토리얼 열기'}).click();
await page.getByRole('dialog').waitFor();
await page.getByRole('button',{name:'다음',exact:true}).click();
await page.getByRole('heading',{name:'한 프레임으로 먼저 확인하세요.'}).waitFor();
await page.getByRole('button',{name:'닫기',exact:true}).click();
await mkdir('src/tests/artifacts',{recursive:true});
await page.screenshot({path:'src/tests/artifacts/light-ui.png'});
await page.getByRole('button',{name:'테마 전환'}).click();
await page.screenshot({path:'src/tests/artifacts/dark-ui.png'});
assert.deepEqual(errors,[]);
console.log('PASS: empty state, map selection, map tabs, advanced mode, theme toggle, settings, tutorial, no browser exceptions.');

const fixture=await browser.newPage({viewport:{width:1280,height:900}});
fixture.on('pageerror',e=>errors.push(e.message));
await fixture.addInitScript(()=>{
  const svg=(a,b)=>'data:image/svg+xml;base64,'+btoa(`<svg xmlns="http://www.w3.org/2000/svg" width="800" height="450"><defs><linearGradient id="g"><stop stop-color="${a}"/><stop offset="1" stop-color="${b}"/></linearGradient></defs><rect width="800" height="450" fill="url(#g)"/><circle cx="400" cy="230" r="100" fill="white" opacity=".4"/></svg>`);
  const source=svg('#596e89','#a4ae92'),depth=svg('#111111','#dddddd'),normal=svg('#8899dd','#ca97db');
  let prefs={theme:'dark',outputDir:'C:\\UI-Test-Output',tutorialDone:true,onboardingDone:true,startupWorkspace:'depth',autoUpdate:true,options:{maps:['depth','normal'],processingMode:'fast',previewMap:'depth',normalStrength:1,steps:4,model:'image-small',inputSize:280,nearWhite:true,gamma:1,contrast:.5,device:'auto',precision:'auto',outputSize:'source',codec:'h264'}};
  window.depthdesk={getPreferences:async()=>prefs,setPreferences:async p=>(prefs={...prefs,...p}),chooseVideo:async()=>source,getFilePath:()=>source,pasteClipboardImage:async()=>source,probeVideo:async()=>({kind:'image',path:source,name:'ui-test-image.png',width:800,height:450,fps:1,frames:1,duration:1,hasAudio:false}),preview:async()=>({source,image:depth,images:{source,depth,normal},frame:0,width:800,height:450,elapsed:0}),render:async()=>({outputPath:'C:\\UI-Test-Output\\fixture_depth.png',outputPaths:{depth:'fixture_depth.png',normal:'fixture_normal.png'},frames:1,elapsed:0,fps:0}),cancelJob:async()=>{},chooseOutputDir:async()=>null,chooseSavePath:async()=>null,openFolder:async()=>{},revealFile:async()=>{},getRuntime:async()=>({ready:true,installing:false,progress:1,message:'UI TEST FIXTURE'}),installRuntime:async()=>({ready:true,installing:false,progress:1,message:'UI TEST FIXTURE'}),getSystem:async()=>({cuda:false,gpu:'UI TEST FIXTURE',vramGB:0,freeVramGB:0,torch:'test',python:'test',ffmpeg:true}),checkForUpdates:async()=>{},installUpdate:async()=>{},onProgress:()=>()=>{},onRuntime:()=>()=>{},onUpdate:()=>()=>{}};
});
await fixture.addInitScript(()=>{
  window.depthdesk.onCloakProgress=()=>()=>{};
  window.depthdesk.chooseCloakFiles=async()=>[];
  const catalog={basicReady:true,models:['image-small','video-small','alpha-fast','alpha-advanced','normal','appearance'].map(id=>({id,name:id,ready:true,builtin:id.endsWith('small'),repo:'UI TEST FIXTURE',revision:'test',license:'test'}))};
  window.depthdesk.getModelCatalog=async()=>catalog;
  window.depthdesk.downloadModel=async()=>{throw new Error('Unexpected model download in UI fixture');};
  window.depthdesk.cancelModelDownload=async()=>{};
  window.depthdesk.onModelProgress=()=>()=>{};
  window.depthdesk.getUpdateStatus=async()=>({status:'idle'});
  window.depthdesk.downloadUpdate=async()=>{};
  window.depthdesk.preparePlayback=async({path})=>({path,proxy:false,cached:true});
  window.depthdesk.cancelPlayback=async()=>{};
  window.depthdesk.onPlaybackProgress=()=>()=>{};
  window.depthdesk.getRuntime=async()=>({ready:true,depthModelsReady:true,cloakReady:true,installing:false,progress:1,message:'UI TEST FIXTURE'});
});
await fixture.goto(process.env.UI_TEST_URL??'http://127.0.0.1:5173');
await fixture.getByRole('button',{name:'파일 선택'}).click();
await fixture.getByText('ui-test-image.png',{exact:true}).waitFor();
assert.equal(await fixture.getByText('구간 자르기',{exact:true}).count(),0);
await fixture.getByRole('button',{name:'이미지 미리보기',exact:true}).click();
await fixture.getByAltText('depth 추정 맵').waitFor();
await fixture.getByRole('tab',{name:'Normal',exact:true}).click();
await fixture.getByAltText('normal 추정 맵').waitFor();
await fixture.getByRole('slider',{name:'원본과 맵 비교 경계'}).fill('65');
await fixture.getByRole('button',{name:'2개 맵 이미지 내보내기'}).click();
await fixture.getByText('이미지 맵이 완성되었습니다.',{exact:true}).waitFor();
assert.deepEqual(errors,[]);
console.log('PASS: image load, no video controls, preview, map switching, comparison slider, multi-map export UI (explicit mocked backend fixture).');
const videoFixture='src/tests/artifacts/fixture.mp4';
const ffmpeg=spawnSync(process.env.FFMPEG_PATH??'ffmpeg',['-hide_banner','-loglevel','error','-y','-f','lavfi','-i','testsrc2=size=640x360:rate=30','-t','2','-c:v','libx264','-pix_fmt','yuv420p',videoFixture],{encoding:'utf8'});
assert.equal(ffmpeg.status,0,ffmpeg.stderr);
const videoPage=await browser.newPage({viewport:{width:1280,height:900}});
videoPage.on('pageerror',e=>errors.push(e.message));
await videoPage.addInitScript(()=>localStorage.setItem('depthdesk-demo',JSON.stringify({onboardingDone:true,startupWorkspace:'depth'})));
await videoPage.goto(process.env.UI_TEST_URL??'http://127.0.0.1:5173');
const chooserPromise=videoPage.waitForEvent('filechooser');
await videoPage.getByRole('button',{name:'파일 선택'}).click();
const chooser=await chooserPromise;await chooser.setFiles(videoFixture);
await videoPage.getByText('fixture.mp4',{exact:true}).waitFor();
assert.equal(await videoPage.getByTestId('video-trim-editor').count(),0);
await videoPage.getByRole('button',{name:'다음 프레임',exact:true}).click();
await videoPage.getByTestId('video-trim-open').click();
await videoPage.getByTestId('video-trim-start-handle').press('ArrowRight');
assert.ok(Number(await videoPage.getByRole('spinbutton',{name:'자르기 시작 초',exact:true}).inputValue())>0);
await videoPage.getByRole('spinbutton',{name:'자르기 종료 초',exact:true}).fill('1.5');
await videoPage.getByTestId('video-trim-apply').click();
await videoPage.getByTestId('video-trim-open').click();
assert.equal(Number(await videoPage.getByRole('spinbutton',{name:'자르기 종료 초',exact:true}).inputValue()),1.5);
await videoPage.getByTestId('video-trim-reset').click();
await videoPage.getByRole('button',{name:'원본 재생',exact:true}).click();
await videoPage.waitForTimeout(250);
await videoPage.getByRole('button',{name:'일시 정지',exact:true}).click();
assert.ok(await videoPage.locator('video').evaluate(v=>v.currentTime)>0);
assert.deepEqual(errors,[]);
console.log('PASS: real synthetic-video import, frame stepping, trim boundaries/reset, source playback and pause.');
await browser.close();
